### ISSUE TITLE
Wrong Bonus Id for ilvl 200 Tree-Scaler's Britches

### ISSUE THREAD

**Issue by bagelbits** [simulationcraft/simc-addon#28]
### Describe the bug
`/simc` is giving the "Scales with level" `bonus_id` instead of the ilvl 200 `bonus_id` for [Tree-Scaler's Britches](https://www.wowhead.com/item=184753/tree-scalers-britches):
```
legs=,id=184753,bonus_id=7240,drop_level=60
```

### Expected behavior
Upon running `/simc`, the legs line should be:
```
legs=,id=184753,bonus_id=1587,drop_level=60
```

### To Reproduce
Buy the ilvl 200 [Tree-Scaler's Britches](https://www.wowhead.com/item=184753/tree-scalers-britches) from either Wild Hunt Quartermaster and equip them. Then run `simc`.

### Additional information
* SimulationCraft Version
9.0.2-15

**Comment by seriallos** [comment]
The SimC addon gets the bonus IDs from WoW itself via the Lua API / parsing item links so it can't really be wrong. Blizzard implemented the item using bonus ID 7240, not 1587. [Bonus 7240](https://wow.tools/dbc/?dbc=itembonus&build=9.0.2.37176#page=1&search=7240) indicates that [item curve 24245](https://wow.tools/dbc/?dbc=curvepoint&build=9.0.2.37176#page=1&search=24245) is used to resolve the item level based on what level it dropped at - this item curve ends up being a little bit odd since it can only resolve to ilevel 200.

If I'm missing some context, let me know. But as far as I can tell, the bonus ID being emitted is correct.
