### ISSUE TITLE
/simc [item] from Place Order window

### ISSUE THREAD

**Issue by Discomanco** [simulationcraft/simc-addon#45]
When doing `/simc [item]` with the previewed item from the Place Crafting Order NPCs, the output string does not contain any data apart from `bonus_id=3524` and crafting quality.

Place Order window and item preview
![image](https://github.com/seriallos/raidbots-issues/assets/4707702/2b155b63-ceb0-4f5f-ba95-40604321a01d)
Addon command with previewed item
![image](https://github.com/seriallos/raidbots-issues/assets/4707702/9c60d44f-29c8-4a05-a178-502fdf50fa61)
Output string
```
### Linked gear
#
# Torc of Passed Time
# neck=,id=201759,bonus_id=3524,crafting_quality=1
```

Looking at some of the item dumps, when the preview item is linked, whether it's a fresh craft or recraft, it only has the 3524 bonus, +stats bonuses, crafting quality and flavor text - a flavor text that would normally be added from the Spark bonus ID.
Possible solution: Look for the flavor text in the item link (206959) and add the Spark bonus ID to the string?

**Comment by seriallos** [comment]
These item links in-game are using an unusual format to encode the crafting data. Rather than using bonus IDs (which would be present in a "real" item once crafted), it looks like the game client is encoding the item with some of the crafting materials in the item link. This isn't a format that Raidbots/SimC/Wowhead/etc understand and I'm not aware of a supported way to map these to bonus IDs in the addon - if there was, the game client would likely already be doing it.

WoW does a few other weird item links in places like the Dungeon Journal that don't quite work when using the /simc addon. Basically, if the item isn't actually in your bag or on your character, it may not be possible to get accurate item string data for it.

There's no good workaround in the addon itself (even with tooltip scraping). In SimC itself you can manually edit the item strings in certain ways and adjust the item level. On Raidbots you can use Gear Compare or Droptimizer to test out items you don't have.
