### ISSUE TITLE
[Request] API to extend the generated output?

### ISSUE THREAD

**Issue by drnoonien** [simulationcraft/simc-addon#47]
Hi, I have a use-case where I use an addon to manage my talents, meaning I only store one build in the official Blizzard manager and instead use a separate storage source for all my actual builds.

This has the unfortunate downside that `/simc` doesn't pick up any of my builds. Is there somewhere I can hook in to extend the generated simc string with my own talent export strings? If not, would it be possible to add that as a public API that other addons could use to add to the output string?

**Comment by seriallos** [comment]
No plans for "official" support for anything but loadouts from the base UI.

I believe several of the 3rd party load out addons have figured out a way to append data to the /simc window. The major request is that you don't mess with the checksum from the SimC addon since that acts as a soft indicator that the input has come directly from the SimC addon without anything else messing with it.

This is all to avoid chasing my own tail when debugging issues with input. It's regularly been an issue where users/addons mess with the /simc input in ways that can break sims or provide unexpected/invalid results.
